#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
#Window decoration
bspc config border_width 2
bspc config window_gap 25

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
#Border color
bspc config normal_border_color "#08D9D6"
bspc config active_border_color "#08D9D6"
bspc config focused_border_color "#08D9D6"

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
picom --experimental-backends -b
nitrogen --restore &
killall notification-daemon
killall dunst
dunst -config ~/.config/dunst/dunstrc &
$HOME/.config/polybar/launch.sh &
# polybar &
#Cursor
xsetroot -cursor_name left_ptr &
