#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V
#Window decoration
bspc config border_width 1
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
#Border color
bspc config normal_border_color "#FFFFFF"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#FFFFFF"
#bspc config focused_border_color "#08D9D6"

#AutoStart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
picom --experimental-backends -b
nitrogen --restore &
killall notification-daemon
killall dunst
dunst -config ~/.config/dunst/dunstrc &
$HOME/.config/polybar/launch.sh &
# polybar &
#Cursor
xsetroot -cursor_name left_ptr &
