#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         3
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh
#polybar &
