;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[mocha]
background = #1E1E2E
background-alt = #11111b
foreground = #cdd6f4
primary = #cdd6f4
secondary = #a6adc8
alert = #f38ba8
disabled = #45475a

include-file = /home/ankush/.config/polybar/modules.ini
; include-file = /home/ankush/.config/polybar/fonts.ini

[bar/mybar]
width = 99.8%
height = 30pt
radius = 12
dpi = 96
background = ${mocha.background}
foreground = ${mocha.foreground}
line-size = 3pt
fixed-center = true
border-left-size = 12
border-right-size = 12
border-top-size = 12
border-color = #00000000
offset-x = 0
offset-y = 0
padding-left = 2
padding-right = 2
margin-top = 1
margin-bottom = 1
separator = |
modules-center = bspwm
modules-left = date
modules-right = pulseaudio wlan battery
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
font-0 = monospace;2
; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3
; override-redirect = true
[settings]
screenchange-reload = true
pseudo-transparency = true
; vim:ft=dosini

