;--------------------------------------------
; modules                                   ;
;--------------------------------------------

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${mocha.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = ""
format-volume-prefix-foreground = ${mocha.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${mocha.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${mocha.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${mocha.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
format-connected-prefix = "%{F#dbbc7f}%{F-}  "
label-connected = On

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %a,%I:%M
date-alt = %Y-%m-%d %I:%M:%S

label = %date%
label-foreground = ${mocha.primary}

; [module/battery]
; type = internal/battery
; format-prefix = "Battery"
; format-prefix-foreground = ${mocha.primary}
; full-at = 99
; low-at = 5
; battery = BAT0
; adapter = ACAD
; poll-interval = 5
; format-foreground = ${color.foreground}
; format-background = ${color.background}
;
[module/battery]
type = internal/battery
battery = BAT0
adapter = ACAD
time-format = %H:%m
format-charging-prefix ="%{F#f1739d}%{F-}  "
label-charging = %percentage%%
label-charging-padding-right = ${padding.modules}
label-charging-font = 5

format-discharging-prefix ="%{F#f1739d}%{F-}  "
label-discharging = %percentage%%
label-discharging-padding-right = ${padding.modules}
label-discharging-font = 5

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = false
enble-click = true
reverse-scroll = true
fuzzy-match = true
occupied-scroll = true

label-active = %name%
label-active-background = ${mocha.background-alt}
label-active-underline= ${mocha.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${mocha.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${mocha.disabled}
label-empty-padding = 1

